// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9Knry9U7hSHcb3iQC97cFoit-3R9urY',
    appId: '1:494834619390:web:0a72de21a0d2d703e326af',
    messagingSenderId: '494834619390',
    projectId: 'draft1-b8d31',
    authDomain: 'draft1-b8d31.firebaseapp.com',
    storageBucket: 'draft1-b8d31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4tlPBOqyPpKpMH4lgJKf1-G105EHXzk',
    appId: '1:494834619390:android:ee1411e65a9c8788e326af',
    messagingSenderId: '494834619390',
    projectId: 'draft1-b8d31',
    storageBucket: 'draft1-b8d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHhZiUjzwklz_TE5DPPFA83h3BZeC8xo',
    appId: '1:494834619390:ios:f11567023ab264dbe326af',
    messagingSenderId: '494834619390',
    projectId: 'draft1-b8d31',
    storageBucket: 'draft1-b8d31.firebasestorage.app',
    iosBundleId: 'com.example.draft1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnHhZiUjzwklz_TE5DPPFA83h3BZeC8xo',
    appId: '1:494834619390:ios:f11567023ab264dbe326af',
    messagingSenderId: '494834619390',
    projectId: 'draft1-b8d31',
    storageBucket: 'draft1-b8d31.firebasestorage.app',
    iosBundleId: 'com.example.draft1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp9Knry9U7hSHcb3iQC97cFoit-3R9urY',
    appId: '1:494834619390:web:6e210dabd05b3761e326af',
    messagingSenderId: '494834619390',
    projectId: 'draft1-b8d31',
    authDomain: 'draft1-b8d31.firebaseapp.com',
    storageBucket: 'draft1-b8d31.firebasestorage.app',
  );
}
